name: Security Audit

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [main]
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run security audit
        run: npm audit --audit-level=high || true
        
      - name: Upload audit results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-audit-results
          path: |
            npm-audit.json
            package-lock.json
          retention-days: 30
          
      - name: Create issue if vulnerabilities found
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let auditOutput = '';
            try {
              auditOutput = fs.readFileSync('npm-audit.json', 'utf8');
            } catch (e) {
              auditOutput = 'Security audit failed - check logs for details';
            }
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Security vulnerabilities detected',
              body: `## Security Audit Results
            
            High severity vulnerabilities were detected during the automated security audit.
            
            ### Audit Output:
            \`\`\`json
            ${auditOutput}
            \`\`\`
            
            ### Next Steps:
            1. Review the vulnerabilities
            2. Update affected dependencies
            3. Test thoroughly
            4. Deploy fixes
            
            **Priority:** High
            **Assigned to:** @alexis_mla`,
              labels: ['security', 'high-priority', 'automated'],
              assignees: ['alexis_mla']
            });
